development:
  dialect: "mysql"
  database: "cmb_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "perview2017"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/cmb_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/cmb_production?parseTime=true&multiStatements=true&readTimeout=1s"}}